orjson support
yukinarit/pyserde pull request #226
Opened 2022-05-11 10:05 UTC by kigawas

Closes #73 

Notable change: `to_json` now returns `bytes` in lieu of `str`

2022-05-16 08:36 UTC, kigawas commented
@yukinarit You can review when you have time

2022-05-16 13:12 UTC, yukinarit commented
@kmsquire Could you review?

2022-05-22 13:04 UTC, yukinarit requested changes

2022-05-22 13:04 UTC, yukinarit commented on serde/json.py
> +        return json.dumps(obj, ensure_ascii=False, separators=(",", ":"), **opts)
Could you fix to allow users to pass own `ensure_ascii` and `separators` variables in `to_json` like this? 

```python
ensure_ascii = opts.pop("ensure_ascii", False)
separators = opts.pop("separators", (",", ":"))
return json.dumps(obj, ensure_ascii=ensure_ascii, separators=separators, **opts)
```

I got this error without it
```
TypeError: json.dumps() got multiple values for keyword argument 'separators
```

2022-05-23 12:54 UTC, yukinarit approved these changes
LGTM!

2022-05-23 12:54 UTC, merged

2022-05-23 18:40 UTC, kmsquire commented
Sorry not to review sooner--I've been pretty busy--but glad this is merged.  Cheers!

2022-05-23 23:16 UTC, yukinarit commented
@kmsquire 
No worries, and thank you so much! If you find anything is missing for numpy support, please report 👍